name: "Test & Build"

on:
  push: { }
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libasound2-dev

      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Init project
        run: make init

      - name: Test
        run: make all-test
        shell: bash

      - name: Build
        run: make build-all
        shell: bash

      - name: Show build result
        run: make show-build-result
        shell: bash
